### PR TITLE
Typos correction

### PR DESCRIPTION
**Pull request by Shibu778**
Dear Geert Jan Bex,
I was going through this awesome repository on Fortran-MOOC. I came across some typos which can be corrected. I am still going through other parts of this repository and will try to suggest further improvement. By the way this is one of the best Fortran resources that I could find in internet. Thanks for making it.

I could not locate a development branch so creating a merge request to master branch.

### CODE REVIEW

**Review by gjbex — COMMENTED** [review]
Please keep in mind that this is not standard markdown, but rather intended for use on FutureLearn.  Their dialect of markdown uses '$$' to delimited inline LaTeX expressions.

**Review by gjbex — APPROVED** [review]

**Review by gjbex — APPROVED** [review]

**Review by gjbex — APPROVED** [review]

**Review by gjbex — COMMENTED** [review]
Thanks, you are right there is a typo, but the correction should be 'you would'.

**Comment by gjbex** [comment]
Thanks for the pull request, unfortunately I can't merge it without changes (see comments).

You point out some good points, I'll correct the typos you mention.

**Comment by Shibu778** [comment]
Thank you for your reply. I have taken care of points you have mentioned. Please check.

**Review by gjbex — APPROVED** [review]

**Review by gjbex — APPROVED** [review]

**Pull request merged**
